<?php

namespace DSchoenbauer\Exception\Platform;

use DSchoenbauer\Exception\ExceptionInterface;
use DSchoenbauer\Tests\Exception\Platform\AbstractPlatformException;


/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-21 at 21:37:50.
 */
class BadMethodCallExceptionTest extends AbstractPlatformException {

    /**
     * @var BadMethodCallException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BadMethodCallException;
        $this->setCommonInterface(ExceptionInterface::class)->setParentClass(\BadMethodCallException::class);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
