<?php

namespace DSchoenbauer\Exception\Http\ServerError;

use DSchoenbauer\Exception\ExceptionInterface;
use DSchoenbauer\Exception\Http\ClientError\InternalServerErrorException;
use DSchoenbauer\Tests\Exception\Http\AbstractHttpException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-21 at 21:37:47.
 */
class InternalServerErrorExceptionTest extends AbstractHttpException {

    /**
     * @var InternalServerError
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new InternalServerErrorException;
        $this->setCommonInterface(ExceptionInterface::class)
        ->setParentClass(ServerErrorException::class)
        ->setErrorNumber(500);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
