<?php

namespace DSchoenbauer\Exception\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-21 at 21:37:47.
 */
class BadRequestExceptionTest extends \DSchoenbauer\Tests\Exception\Http\AbstractHttpException{

    /**
     * @var BadRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BadRequestException;
        $this->setCommonInterface(\DSchoenbauer\Exception\ExceptionInterface::class)
                ->setParentClass(\DSchoenbauer\Exception\Platform\InvalidArgumentException::class)
                ->setErrorNumber(400);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
