<?php

namespace DSchoenbauer\Exception\Http\ClientError;

use DSchoenbauer\Exception\ExceptionInterface;
use DSchoenbauer\Tests\Exception\Http\AbstractHttpException;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-02-21 at 21:37:46.
 */
class UnsupportedMediaTypeExceptionTest extends AbstractHttpException {

    /**
     * @var Unauthorized
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new UnsupportedMediaTypeException;
        $this->setCommonInterface(ExceptionInterface::class)
        ->setParentClass(ClientErrorException::class)
        ->setErrorNumber(415);
    }
    
    public function testSupportedMediaTypes(){
        $mediaTypes = ['doc','docx'];
        $this->assertEquals($mediaTypes, $this->object->setSupportedMediaTypes($mediaTypes)->getSupportedMediaTypes());
    }
    
    public function testSupportedMediaTypesThroughConstruct(){
        $mediaTypes = ['doc','docx','pdf'];
        $exc = new UnsupportedMediaTypeException($mediaTypes);
        $this->assertEquals($mediaTypes, $exc->getSupportedMediaTypes());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
